// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Secure.Presistence.Context;

#nullable disable

namespace Secure.Application.Presistence.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20230825132453_RegisterMockWSDLSqlSchemaMigration")]
    partial class RegisterMockWSDLSqlSchemaMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Secure.Domain.Entity.OptionsList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OptionId")
                        .HasColumnType("int");

                    b.Property<string>("OptionName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ResponseWsdlsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResponseWsdlsId");

                    b.ToTable("OptionsLists");
                });

            modelBuilder.Entity("Secure.Domain.Entity.ResponseWsdl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BucketId")
                        .HasColumnType("int");

                    b.Property<string>("BucketName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Dial")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool?>("IsRnR")
                        .HasColumnType("bit");

                    b.Property<string>("RnRText")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ResponseWsdls");
                });

            modelBuilder.Entity("Secure.Domain.Entity.OptionsList", b =>
                {
                    b.HasOne("Secure.Domain.Entity.ResponseWsdl", "ResponseWsdls")
                        .WithMany("OptionsList")
                        .HasForeignKey("ResponseWsdlsId");

                    b.Navigation("ResponseWsdls");
                });

            modelBuilder.Entity("Secure.Domain.Entity.ResponseWsdl", b =>
                {
                    b.Navigation("OptionsList");
                });
#pragma warning restore 612, 618
        }
    }
}
