//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsdlService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://eaidev.mobinil.com/MEAI_OnlineServices_2017.webServices.GO", ConfigurationName="WsdlService.checkDataProfileStatus_V2_WSDL_PortType")]
    public interface checkDataProfileStatus_V2_WSDL_PortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="MEAI_OnlineServices_2017_webServices_GO_checkDataProfileStatus_V2_WSDL_Binder_che" +
            "ckDataProfileStatus_V2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WsdlService.checkDataProfileStatus_V2Response> checkDataProfileStatus_V2Async(WsdlService.checkDataProfileStatus_V2Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eaidev.mobinil.com/MEAI_OnlineServices_2017.webServices.GO")]
    public partial class checkDataProfileStatus_in
    {
        
        private string dialField;
        
        private string sourceIdField;
        
        private string langIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string dial
        {
            get
            {
                return this.dialField;
            }
            set
            {
                this.dialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string sourceId
        {
            get
            {
                return this.sourceIdField;
            }
            set
            {
                this.sourceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string langId
        {
            get
            {
                return this.langIdField;
            }
            set
            {
                this.langIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eaidev.mobinil.com/MEAI_OnlineServices_2017.webServices.GO")]
    public partial class errorDoc
    {
        
        private string statusField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eaidev.mobinil.com/MEAI_OnlineServices_2017.webServices.GO")]
    public partial class optionsList
    {
        
        private string optionNameField;
        
        private string optionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string optionName
        {
            get
            {
                return this.optionNameField;
            }
            set
            {
                this.optionNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string optionId
        {
            get
            {
                return this.optionIdField;
            }
            set
            {
                this.optionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eaidev.mobinil.com/MEAI_OnlineServices_2017.webServices.GO")]
    public partial class BucketInfo
    {
        
        private string currentBucketIdField;
        
        private string currentBucketNameField;
        
        private string isRnRField;
        
        private string rnRTextField;
        
        private optionsList[] optionsListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string currentBucketId
        {
            get
            {
                return this.currentBucketIdField;
            }
            set
            {
                this.currentBucketIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string currentBucketName
        {
            get
            {
                return this.currentBucketNameField;
            }
            set
            {
                this.currentBucketNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string IsRnR
        {
            get
            {
                return this.isRnRField;
            }
            set
            {
                this.isRnRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string RnRText
        {
            get
            {
                return this.rnRTextField;
            }
            set
            {
                this.rnRTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("optionsList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public optionsList[] optionsList
        {
            get
            {
                return this.optionsListField;
            }
            set
            {
                this.optionsListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://eaidev.mobinil.com/MEAI_OnlineServices_2017.webServices.GO")]
    public partial class checkDataProfileStatus_out
    {
        
        private BucketInfo[] bucketInfoField;
        
        private errorDoc errorDocField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BucketInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public BucketInfo[] BucketInfo
        {
            get
            {
                return this.bucketInfoField;
            }
            set
            {
                this.bucketInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public errorDoc errorDoc
        {
            get
            {
                return this.errorDocField;
            }
            set
            {
                this.errorDocField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkDataProfileStatus_V2", WrapperNamespace="http://eaidev.mobinil.com/MEAI_OnlineServices_2017.webServices.GO", IsWrapped=true)]
    public partial class checkDataProfileStatus_V2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eaidev.mobinil.com/MEAI_OnlineServices_2017.webServices.GO", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public WsdlService.checkDataProfileStatus_in checkDataProfileStatus_in;
        
        public checkDataProfileStatus_V2Request()
        {
        }
        
        public checkDataProfileStatus_V2Request(WsdlService.checkDataProfileStatus_in checkDataProfileStatus_in)
        {
            this.checkDataProfileStatus_in = checkDataProfileStatus_in;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkDataProfileStatus_V2Response", WrapperNamespace="http://eaidev.mobinil.com/MEAI_OnlineServices_2017.webServices.GO", IsWrapped=true)]
    public partial class checkDataProfileStatus_V2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://eaidev.mobinil.com/MEAI_OnlineServices_2017.webServices.GO", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public WsdlService.checkDataProfileStatus_out checkDataProfileStatus_out;
        
        public checkDataProfileStatus_V2Response()
        {
        }
        
        public checkDataProfileStatus_V2Response(WsdlService.checkDataProfileStatus_out checkDataProfileStatus_out)
        {
            this.checkDataProfileStatus_out = checkDataProfileStatus_out;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface checkDataProfileStatus_V2_WSDL_PortTypeChannel : WsdlService.checkDataProfileStatus_V2_WSDL_PortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class checkDataProfileStatus_V2_WSDL_PortTypeClient : System.ServiceModel.ClientBase<WsdlService.checkDataProfileStatus_V2_WSDL_PortType>, WsdlService.checkDataProfileStatus_V2_WSDL_PortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public checkDataProfileStatus_V2_WSDL_PortTypeClient() : 
                base(checkDataProfileStatus_V2_WSDL_PortTypeClient.GetDefaultBinding(), checkDataProfileStatus_V2_WSDL_PortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MEAI_OnlineServices_2017_webServices_GO_checkDataProfileStatus_V2_WSDL_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public checkDataProfileStatus_V2_WSDL_PortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(checkDataProfileStatus_V2_WSDL_PortTypeClient.GetBindingForEndpoint(endpointConfiguration), checkDataProfileStatus_V2_WSDL_PortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public checkDataProfileStatus_V2_WSDL_PortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(checkDataProfileStatus_V2_WSDL_PortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public checkDataProfileStatus_V2_WSDL_PortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(checkDataProfileStatus_V2_WSDL_PortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public checkDataProfileStatus_V2_WSDL_PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WsdlService.checkDataProfileStatus_V2Response> WsdlService.checkDataProfileStatus_V2_WSDL_PortType.checkDataProfileStatus_V2Async(WsdlService.checkDataProfileStatus_V2Request request)
        {
            return base.Channel.checkDataProfileStatus_V2Async(request);
        }
        
        public System.Threading.Tasks.Task<WsdlService.checkDataProfileStatus_V2Response> checkDataProfileStatus_V2Async(WsdlService.checkDataProfileStatus_in checkDataProfileStatus_in)
        {
            WsdlService.checkDataProfileStatus_V2Request inValue = new WsdlService.checkDataProfileStatus_V2Request();
            inValue.checkDataProfileStatus_in = checkDataProfileStatus_in;
            return ((WsdlService.checkDataProfileStatus_V2_WSDL_PortType)(this)).checkDataProfileStatus_V2Async(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MEAI_OnlineServices_2017_webServices_GO_checkDataProfileStatus_V2_WSDL_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MEAI_OnlineServices_2017_webServices_GO_checkDataProfileStatus_V2_WSDL_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://eaidev.mobinil.com:5555/ws/MEAI_OnlineServices_2017.webServices.GO.checkDa" +
                        "taProfileStatus_V2_WSDL/MEAI_OnlineServices_2017_webServices_GO_checkDataProfile" +
                        "Status_V2_WSDL_Port");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return checkDataProfileStatus_V2_WSDL_PortTypeClient.GetBindingForEndpoint(EndpointConfiguration.MEAI_OnlineServices_2017_webServices_GO_checkDataProfileStatus_V2_WSDL_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return checkDataProfileStatus_V2_WSDL_PortTypeClient.GetEndpointAddress(EndpointConfiguration.MEAI_OnlineServices_2017_webServices_GO_checkDataProfileStatus_V2_WSDL_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            MEAI_OnlineServices_2017_webServices_GO_checkDataProfileStatus_V2_WSDL_Port,
        }
    }
}
